- name: Get source
  get_url:
    url: "{{ libpsml_url }}"
    dest: "{{ libpsml_code_folder }}/{{ libpsml_src_archive }}"
  register: libpsml_download

- name: Extract libpsml source
  unarchive:
    src: "{{ libpsml_download.dest }}"
    dest: "{{ libpsml_code_folder }}"
    remote_src: true

- name: Configure libpsml
  shell: ./configure --with-xmlf90={{ xmlf90_prefix }} --prefix={{ libpsml_prefix }}
  args:
    chdir: "{{ libpsml_topdir }}"
    creates: "{{ libpsml_topdir }}/Makefile"
  register: libpsml_configure


- name: Make libpsml
  shell: "make"
  args:
    chdir: "{{ libpsml_topdir }}"
    creates: "{{ libpsml_topdir }}/src/libpsml.la"
  register: libpsml_make

- name: Install libpsml
  shell: make install
  args:
    chdir: "{{ libpsml_topdir }}"
    creates: "{{ libpsml_prefix }}/lib/libpsml.a"
  become: yes
  register: libpsml_install
