# see https://pelios.csx.cam.ac.uk/~mc321/siesta.html
- name: Install siesta dependencies
  become: true
  apt:
    name:
    - gfortran
    - make
    - openmpi-common
    - openmpi-bin
    - libopenmpi-dev
    - libnetcdf-dev
    - netcdf-bin
    - libnetcdff-dev
    - libscalapack-mpi-dev
    - libblas-dev
    - liblapack-dev
    - unzip
    - libfftw3-dev

# Compile and install flook
- include: flook.yml
  when: siesta_enable_flook == '1'

# Compile and install xmlf90
- include: xmlf90.yml

# Compile and install libpsml
- include: libpsml.yml

# Compile and install libgridxc
- include: gridxc-multi.yml

# Compile and install Siesta and utilities
- include: siesta.yml

# Install pseudopotentials
- include: psml-pps.yml
  tags: siesta_psml_pps
