# running all tests would take of the order of 1h
# there is currently a bug that results in the test failing
# https://bugs.launchpad.net/siesta/+bug/1725813

#
# Use --oversubscribe in case there is only one core in the virtual machine...
#

- name: run siesta tests
  shell: make clean; make MPI='mpirun --oversubscribe -np 2' check
  args:
    chdir: "{{ siesta_topdir }}/Obj/Tests/{{ item }}"
  with_items: "{{ siesta_tests }}"
  tags: tests

- name: run siesta_lua tests
  shell: make clean; make MPI='mpirun --oversubscribe -np 2' check
  args:
    chdir: "{{ siesta_topdir }}/Obj/Tests/{{ item }}"
  with_items: "{{ siesta_lua_tests }}"
  when: siesta_enable_flook | bool
  tags: tests

# fails (return code != 0), if "Test Failed." is found
# - name: check siesta test results
#   command: grep -vFxq "Test Failed." "{{ siesta_topdir }}/build/Testing/Temporary/LastTest.log"
