- name: Get source
  get_url:
    url: "{{ xmlf90_url }}"
    dest: "{{ xmlf90_code_folder }}/{{ xmlf90_src_archive }}"
  register: xmlf90_download

- name: Extract xmlf90 source
  unarchive:
    src: "{{ xmlf90_download.dest }}"
    dest: "{{ xmlf90_code_folder }}"
    remote_src: true

- name: Configure xmlf90
  shell: ./configure --prefix={{ xmlf90_prefix }}
  args:
    chdir: "{{ xmlf90_topdir }}"
    creates: "{{ xmlf90_topdir }}/Makefile"
  register: xmlf90_configure


- name: Make xmlf90
  shell: "make"
  args:
    chdir: "{{ xmlf90_topdir }}"
    creates: "{{ xmlf90_topdir }}/src/libxmlf90.la"
  register: xmlf90_make

- name: Install xmlf90
  shell: make install
  args:
    chdir: "{{ xmlf90_topdir }}"
    creates: "{{ xmlf90_prefix }}/lib/libxmlf90.a"
  become: yes
  register: xmlf90_install

